; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_m0]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
board_build.core = adafruit
build_flags = -DUSB_VID=0x239A -DUSB_PID=0x800B -DUSBCON
lib_deps = 
	arduino-libraries/Arduino Low Power@^1.2.2
	paulstoffregen/OneWire@^2.3.8
	khoih-prog/FlashStorage_SAMD@^1.3.2
